"""
ComfyUI-4K4D Node 9: Render
==============================
Renders novel views in multiple modes: spiral, test views, free viewpoint.
Supports H.264, ProRes, and PNG sequence output.
"""

import logging
import os
from pathlib import Path

from ..core.base_node import BaseEasyVolcapNode
from ..core.constants import CATEGORIES, DATASET_INFO_TYPE, DEFAULTS
from ..core.subprocess_runner import evc_train_progress_parser

logger = logging.getLogger("4K4D.n09_render")


class FourK4D_Render(BaseEasyVolcapNode):
    """
    Renders novel views from trained 4K4D model.

    Modes:
    - spiral: Free-viewpoint spiral camera path
    - test_views: Render from input camera angles
    - free_viewpoint: Custom camera path
    """

    CATEGORY = CATEGORIES["rendering"]
    FUNCTION = "execute"
    RETURN_TYPES = (DATASET_INFO_TYPE, "STRING", "STRING", "STRING", "STRING", "IMAGE")
    RETURN_NAMES = ("dataset_info", "mp4_path", "prores_path", "frames_dir", "ply_output_dir", "preview_frame")
    OUTPUT_NODE = True

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "dataset_info": (DATASET_INFO_TYPE,),
                "render_mode": (["spiral", "test_views", "free_viewpoint"],),
            },
            "optional": {
                "frame_sample": ("STRING", {"default": "0,None,1"}),
                "n_render_views": ("INT", {"default": 300, "min": 10, "max": 2000}),
                "focal_ratio": ("FLOAT", {"default": 0.5, "min": 0.1, "max": 2.0, "step": 0.1}),
                "use_cuda_rasterizer": ("BOOLEAN", {"default": True}),
                "output_format": (["mp4_h264", "mp4_prores", "png_sequence", "all"], {"default": "mp4_h264"}),
                "render_resolution": (["1080p", "4K", "match_input"], {"default": "1080p"}),
                "crf": ("INT", {"default": 18, "min": 0, "max": 51}),
            },
            "hidden": {"unique_id": "UNIQUE_ID"},
        }

    def execute(self, dataset_info, render_mode, frame_sample="0,None,1",
                n_render_views=300, focal_ratio=0.5, use_cuda_rasterizer=True,
                output_format="mp4_h264", render_resolution="1080p", crf=18,
                unique_id=None):
        return self._safe_execute(
            self._run, dataset_info, render_mode, frame_sample, n_render_views,
            focal_ratio, use_cuda_rasterizer, output_format, render_resolution,
            crf, unique_id
        )

    def _run(self, dataset_info, render_mode, frame_sample, n_render_views,
             focal_ratio, use_cuda_rasterizer, output_format, render_resolution,
             crf, unique_id):
        self._validate_dataset_info(dataset_info, ["dataset_root", "dataset_name"])

        dataset_root = dataset_info["dataset_root"]
        name = dataset_info["dataset_name"]
        easyvolcap_root = dataset_info.get("easyvolcap_root") or ""
        experiment_name = dataset_info.get("experiment_name") or f"4k4d_{name}"
        config_path = dataset_info.get("config_path") or ""

        runner = self._create_runner()
        render_output_dir = os.path.join(dataset_root, "render_output", render_mode)
        os.makedirs(render_output_dir, exist_ok=True)

        mp4_path = ""
        prores_path = ""
        frames_dir = os.path.join(render_output_dir, "frames")
        ply_dir = os.path.join(render_output_dir, "ply")

        # Check if a model was actually trained before attempting render
        model_path = dataset_info.get("model_path", "")
        if not model_path:
            self._node_logger.warning(
                "No trained model found in dataset_info. "
                "Training must succeed before rendering."
            )
            return (
                dataset_info,
                "",
                "",
                frames_dir,
                ply_dir,
                self._create_error_image("No trained model — training must succeed first"),
            )

        if easyvolcap_root and os.path.exists(easyvolcap_root):
            # Build evc-test command — base architecture config MUST come first,
            # then experiment config, then rendering spec overlays.
            configs = ["configs/exps/4k4d/4k4d_0013_01_r4.yaml"]

            # Experiment config (generated by train node)
            exp_config = dataset_info.get("config_path") or ""
            if not exp_config:
                # Look for the experiment config in the dataset root
                candidate = os.path.join(dataset_root, f"{name}_exp.yaml")
                if os.path.exists(candidate):
                    exp_config = candidate
            if exp_config and os.path.exists(str(exp_config)):
                configs.append(str(exp_config))

            if render_mode == "spiral":
                configs.extend([
                    "configs/specs/superf.yaml",
                    "configs/specs/spiral.yaml",
                    "configs/specs/ibr.yaml",
                    "configs/specs/eval.yaml",
                ])
            elif render_mode == "test_views":
                configs.append("configs/specs/eval.yaml")
            else:
                configs.extend([
                    "configs/specs/eval.yaml",
                    "configs/specs/ibr.yaml",
                ])

            # Determine camera count to prevent view_sample IndexError
            camera_count = dataset_info.get("camera_count", 5)

            # Determine sequence length for temporal rendering
            sequence_length = dataset_info.get("sequence_length", 1)

            # Parse frame_sample — use full sequence if default "0,None,1"
            if frame_sample == "0,None,1" and sequence_length > 1:
                resolved_frame_sample = f"[0,{sequence_length},1]"
            else:
                resolved_frame_sample = f"[{frame_sample}]"

            extra_args = {
                "exp_name": experiment_name,
                "dataloader_cfg.dataset_cfg.data_root": dataset_root,
                "val_dataloader_cfg.dataset_cfg.data_root": dataset_root,
                "val_dataloader_cfg.dataset_cfg.focal_ratio": str(focal_ratio),
                "val_dataloader_cfg.dataset_cfg.n_render_views": str(n_render_views),
                # Limit view_sample to valid camera indices [begin, end, step]
                # This prevents IndexError when spiral/eval configs assume more cameras
                "val_dataloader_cfg.dataset_cfg.view_sample": f"[0,{camera_count},1]",
                # CRITICAL: Include all timesteps for temporal rendering
                # Without this, only frame 0 is rendered (static output)
                "val_dataloader_cfg.dataset_cfg.frame_sample": resolved_frame_sample,
            }

            cmd = self.build_evc_command("evc-test", configs, extra_args)

            # Run from 4K4D repo dir (configs are relative to it)
            fourk4d_root = os.path.join(os.path.dirname(easyvolcap_root), "4K4D")
            render_cwd = fourk4d_root if os.path.isdir(fourk4d_root) else easyvolcap_root

            result = runner.run(
                cmd,
                cwd=render_cwd,
                progress_parser=evc_train_progress_parser,
                unique_id=unique_id,
                timeout_seconds=14400,
            )

            if result.success and experiment_name:
                # Find rendered output — evc-test saves to data/result/{exp_name}/
                # relative to CWD (the 4K4D repo dir), not EasyVolcap
                search_dirs = []
                if render_cwd:
                    search_dirs.append(os.path.join(render_cwd, "data", "result", experiment_name))
                if easyvolcap_root:
                    search_dirs.append(os.path.join(easyvolcap_root, "data", "result", experiment_name))

                for result_dir in search_dirs:
                    if not os.path.exists(result_dir):
                        continue
                    self._node_logger.info(f"Searching for rendered frames in: {result_dir}")
                    # Look for rendered frames (RENDER subdir or direct)
                    for subdir_name in ["RENDER", "render", ""]:
                        check_dir = os.path.join(result_dir, subdir_name) if subdir_name else result_dir
                        if not os.path.isdir(check_dir):
                            continue
                        for f in os.listdir(check_dir):
                            if f.endswith(".jpg") or f.endswith(".png"):
                                frames_dir = check_dir
                                self._node_logger.info(f"Found rendered frames in: {frames_dir}")
                                break
                        if frames_dir != os.path.join(render_output_dir, "frames"):
                            break
                    if frames_dir != os.path.join(render_output_dir, "frames"):
                        break

        # Package output in requested formats
        if os.path.exists(frames_dir) and os.listdir(frames_dir):
            if output_format in ("mp4_h264", "all"):
                mp4_path = os.path.join(render_output_dir, f"{name}_render.mp4")
                self._encode_h264(frames_dir, mp4_path, crf, runner)

            if output_format in ("mp4_prores", "all"):
                prores_path = os.path.join(render_output_dir, f"{name}_render_prores.mov")
                self._encode_prores(frames_dir, prores_path, runner)

        # Generate preview frame
        preview = self._load_preview_frame(frames_dir)

        updated_info = self._update_dataset_info(dataset_info, {
            "render_output": render_output_dir,
        })

        return (
            updated_info,
            mp4_path,
            prores_path,
            frames_dir,
            ply_dir,
            preview,
        )

    def _get_render_frames(self, frames_dir):
        """Get sorted render frames, excluding _error and _gt variants."""
        all_frames = sorted(Path(frames_dir).glob("*.jpg")) + sorted(Path(frames_dir).glob("*.png"))
        # EasyVolcap outputs frame*_camera*.png plus _error.png and _gt.png variants
        # Filter to only the main render images
        render_frames = [
            f for f in all_frames
            if "_error" not in f.stem and "_gt" not in f.stem
        ]
        return render_frames if render_frames else all_frames

    def _create_concat_file(self, frames, output_dir):
        """Create ffmpeg concat file for non-sequential frame names."""
        concat_path = os.path.join(output_dir, "_ffmpeg_concat.txt")
        with open(concat_path, "w") as f:
            for frame in frames:
                f.write(f"file '{frame}'\nduration 0.0333\n")
        return concat_path

    def _encode_h264(self, frames_dir, output_path, crf, runner):
        """Encode frames to H.264 MP4."""
        frames = self._get_render_frames(frames_dir)
        if not frames:
            return

        # Use concat demuxer for non-sequential filenames (EasyVolcap convention)
        concat_file = self._create_concat_file(frames, os.path.dirname(output_path))
        runner.run_simple([
            "ffmpeg", "-y",
            "-f", "concat", "-safe", "0",
            "-i", concat_file,
            "-c:v", "libx264",
            "-crf", str(crf),
            "-pix_fmt", "yuv420p",
            output_path,
        ], timeout=600)

    def _encode_prores(self, frames_dir, output_path, runner):
        """Encode frames to ProRes 4444."""
        frames = self._get_render_frames(frames_dir)
        if not frames:
            return

        concat_file = self._create_concat_file(frames, os.path.dirname(output_path))
        runner.run_simple([
            "ffmpeg", "-y",
            "-f", "concat", "-safe", "0",
            "-i", concat_file,
            "-c:v", "prores_ks",
            "-profile:v", "4444",
            "-pix_fmt", "yuva444p10le",
            output_path,
        ], timeout=600)

    def _load_preview_frame(self, frames_dir):
        """Load first rendered frame as preview."""
        try:
            import numpy as np
            from PIL import Image

            frames_path = Path(frames_dir)
            frames = sorted(frames_path.glob("*.jpg")) + sorted(frames_path.glob("*.png"))
            if frames:
                img = Image.open(frames[0]).convert("RGB")
                img = img.resize((640, 360))
                return self._numpy_to_comfy_image(np.array(img).astype(np.float32) / 255.0)
        except Exception:
            pass
        return self._create_error_image("No rendered frames yet")
