"""
ComfyUI-4K4D Node 9: Render
==============================
Renders novel views in multiple modes: spiral, test views, free viewpoint.
Supports H.264, ProRes, and PNG sequence output.
"""

import logging
import os
import struct
from pathlib import Path

from ..core.base_node import BaseEasyVolcapNode
from ..core.constants import CATEGORIES, DATASET_INFO_TYPE, DEFAULTS
from ..core.subprocess_runner import evc_train_progress_parser

logger = logging.getLogger("4K4D.n09_render")


class FourK4D_Render(BaseEasyVolcapNode):
    """
    Renders novel views from trained 4K4D model.

    Modes:
    - spiral: Free-viewpoint spiral camera path
    - test_views: Render from input camera angles
    - free_viewpoint: Custom camera path
    """

    CATEGORY = CATEGORIES["rendering"]
    FUNCTION = "execute"
    RETURN_TYPES = (DATASET_INFO_TYPE, "STRING", "STRING", "STRING", "STRING", "IMAGE")
    RETURN_NAMES = ("dataset_info", "mp4_path", "prores_path", "frames_dir", "ply_output_dir", "preview_frame")
    OUTPUT_NODE = True

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "dataset_info": (DATASET_INFO_TYPE,),
                "render_mode": (["spiral", "test_views", "free_viewpoint"],),
            },
            "optional": {
                "frame_sample": ("STRING", {"default": "0,None,1"}),
                "n_render_views": ("INT", {"default": 300, "min": 10, "max": 2000}),
                "focal_ratio": ("FLOAT", {"default": 0.5, "min": 0.1, "max": 2.0, "step": 0.1}),
                "use_cuda_rasterizer": ("BOOLEAN", {"default": True}),
                "output_format": (["mp4_h264", "mp4_prores", "png_sequence", "all"], {"default": "mp4_h264"}),
                "render_resolution": (["1080p", "4K", "match_input"], {"default": "1080p"}),
                "crf": ("INT", {"default": 18, "min": 0, "max": 51}),
            },
            "hidden": {"unique_id": "UNIQUE_ID"},
        }

    def execute(self, dataset_info, render_mode, frame_sample="0,None,1",
                n_render_views=300, focal_ratio=0.5, use_cuda_rasterizer=True,
                output_format="mp4_h264", render_resolution="1080p", crf=18,
                unique_id=None):
        return self._safe_execute(
            self._run, dataset_info, render_mode, frame_sample, n_render_views,
            focal_ratio, use_cuda_rasterizer, output_format, render_resolution,
            crf, unique_id
        )

    def _run(self, dataset_info, render_mode, frame_sample, n_render_views,
             focal_ratio, use_cuda_rasterizer, output_format, render_resolution,
             crf, unique_id):
        self._validate_dataset_info(dataset_info, ["dataset_root", "dataset_name"])

        dataset_root = dataset_info["dataset_root"]
        name = dataset_info["dataset_name"]
        easyvolcap_root = dataset_info.get("easyvolcap_root") or ""
        experiment_name = dataset_info.get("experiment_name") or f"4k4d_{name}"
        config_path = dataset_info.get("config_path") or ""

        runner = self._create_runner()
        render_output_dir = os.path.join(dataset_root, "render_output", render_mode)
        os.makedirs(render_output_dir, exist_ok=True)

        mp4_path = ""
        prores_path = ""
        frames_dir = os.path.join(render_output_dir, "frames")
        ply_dir = os.path.join(render_output_dir, "ply")

        # Check if a model was actually trained before attempting render
        model_path = dataset_info.get("model_path", "")
        if not model_path:
            self._node_logger.warning(
                "No trained model found in dataset_info. "
                "Training must succeed before rendering."
            )
            return (
                dataset_info,
                "",
                "",
                frames_dir,
                ply_dir,
                self._create_error_image("No trained model — training must succeed first"),
            )

        # Export PLY point cloud(s) from the trained checkpoint for 3D viewer
        self._export_ply_from_checkpoint(model_path, ply_dir, dataset_info)

        if easyvolcap_root and os.path.exists(easyvolcap_root):
            # Build evc-test command — base architecture config MUST come first,
            # then experiment config, then rendering spec overlays.
            configs = ["configs/exps/4k4d/4k4d_0013_01_r4.yaml"]

            # Experiment config (generated by train node)
            exp_config = dataset_info.get("config_path") or ""
            if not exp_config:
                # Look for the experiment config in the dataset root
                candidate = os.path.join(dataset_root, f"{name}_exp.yaml")
                if os.path.exists(candidate):
                    exp_config = candidate
            if exp_config and os.path.exists(str(exp_config)):
                configs.append(str(exp_config))

            if render_mode == "spiral":
                configs.extend([
                    "configs/specs/superf.yaml",
                    "configs/specs/spiral.yaml",
                    "configs/specs/ibr.yaml",
                    "configs/specs/eval.yaml",
                ])
            elif render_mode == "test_views":
                configs.append("configs/specs/eval.yaml")
            else:
                configs.extend([
                    "configs/specs/eval.yaml",
                    "configs/specs/ibr.yaml",
                ])

            # Determine camera count to prevent view_sample IndexError
            camera_count = dataset_info.get("camera_count", 5)

            # Determine sequence length for temporal rendering
            sequence_length = dataset_info.get("sequence_length", 1)

            # Parse frame_sample — use full sequence if default "0,None,1"
            if frame_sample == "0,None,1" and sequence_length > 1:
                resolved_frame_sample = f"[0,{sequence_length},1]"
            else:
                resolved_frame_sample = f"[{frame_sample}]"

            extra_args = {
                "exp_name": experiment_name,
                "dataloader_cfg.dataset_cfg.data_root": dataset_root,
                "val_dataloader_cfg.dataset_cfg.data_root": dataset_root,
                "val_dataloader_cfg.dataset_cfg.focal_ratio": str(focal_ratio),
                "val_dataloader_cfg.dataset_cfg.n_render_views": str(n_render_views),
                # Limit view_sample to valid camera indices [begin, end, step]
                # This prevents IndexError when spiral/eval configs assume more cameras
                "val_dataloader_cfg.dataset_cfg.view_sample": f"[0,{camera_count},1]",
                # CRITICAL: Include all timesteps for temporal rendering
                # Without this, only frame 0 is rendered (static output)
                "val_dataloader_cfg.dataset_cfg.frame_sample": resolved_frame_sample,
            }

            cmd = self.build_evc_command("evc-test", configs, extra_args)

            # Run from 4K4D repo dir (configs are relative to it)
            fourk4d_root = os.path.join(os.path.dirname(easyvolcap_root), "4K4D")
            render_cwd = fourk4d_root if os.path.isdir(fourk4d_root) else easyvolcap_root

            result = runner.run(
                cmd,
                cwd=render_cwd,
                progress_parser=evc_train_progress_parser,
                unique_id=unique_id,
                timeout_seconds=14400,
            )

            if result.success and experiment_name:
                # Find rendered output — evc-test saves to data/result/{exp_name}/
                # relative to CWD (the 4K4D repo dir), not EasyVolcap
                search_dirs = []
                if render_cwd:
                    search_dirs.append(os.path.join(render_cwd, "data", "result", experiment_name))
                if easyvolcap_root:
                    search_dirs.append(os.path.join(easyvolcap_root, "data", "result", experiment_name))

                for result_dir in search_dirs:
                    if not os.path.exists(result_dir):
                        continue
                    self._node_logger.info(f"Searching for rendered frames in: {result_dir}")
                    # Look for rendered frames (RENDER subdir or direct)
                    for subdir_name in ["RENDER", "render", ""]:
                        check_dir = os.path.join(result_dir, subdir_name) if subdir_name else result_dir
                        if not os.path.isdir(check_dir):
                            continue
                        for f in os.listdir(check_dir):
                            if f.endswith(".jpg") or f.endswith(".png"):
                                frames_dir = check_dir
                                self._node_logger.info(f"Found rendered frames in: {frames_dir}")
                                break
                        if frames_dir != os.path.join(render_output_dir, "frames"):
                            break
                    if frames_dir != os.path.join(render_output_dir, "frames"):
                        break

        # Package output in requested formats
        if os.path.exists(frames_dir) and os.listdir(frames_dir):
            if output_format in ("mp4_h264", "all"):
                mp4_path = os.path.join(render_output_dir, f"{name}_render.mp4")
                self._encode_h264(frames_dir, mp4_path, crf, runner)

            if output_format in ("mp4_prores", "all"):
                prores_path = os.path.join(render_output_dir, f"{name}_render_prores.mov")
                self._encode_prores(frames_dir, prores_path, runner)

        # Generate preview frame
        preview = self._load_preview_frame(frames_dir)

        updated_info = self._update_dataset_info(dataset_info, {
            "render_output": render_output_dir,
            "ply_dir": ply_dir,
        })

        return (
            updated_info,
            mp4_path,
            prores_path,
            frames_dir,
            ply_dir,
            preview,
        )

    def _get_render_frames(self, frames_dir):
        """Get sorted render frames, excluding _error and _gt variants."""
        all_frames = sorted(Path(frames_dir).glob("*.jpg")) + sorted(Path(frames_dir).glob("*.png"))
        # EasyVolcap outputs frame*_camera*.png plus _error.png and _gt.png variants
        # Filter to only the main render images
        render_frames = [
            f for f in all_frames
            if "_error" not in f.stem and "_gt" not in f.stem
        ]
        return render_frames if render_frames else all_frames

    def _create_concat_file(self, frames, output_dir):
        """Create ffmpeg concat file for non-sequential frame names."""
        concat_path = os.path.join(output_dir, "_ffmpeg_concat.txt")
        with open(concat_path, "w") as f:
            for frame in frames:
                f.write(f"file '{frame}'\nduration 0.0333\n")
        return concat_path

    def _encode_h264(self, frames_dir, output_path, crf, runner):
        """Encode frames to H.264 MP4."""
        frames = self._get_render_frames(frames_dir)
        if not frames:
            return

        # Use concat demuxer for non-sequential filenames (EasyVolcap convention)
        concat_file = self._create_concat_file(frames, os.path.dirname(output_path))
        runner.run_simple([
            "ffmpeg", "-y",
            "-f", "concat", "-safe", "0",
            "-i", concat_file,
            "-c:v", "libx264",
            "-crf", str(crf),
            "-pix_fmt", "yuv420p",
            output_path,
        ], timeout=600)

    def _encode_prores(self, frames_dir, output_path, runner):
        """Encode frames to ProRes 4444."""
        frames = self._get_render_frames(frames_dir)
        if not frames:
            return

        concat_file = self._create_concat_file(frames, os.path.dirname(output_path))
        runner.run_simple([
            "ffmpeg", "-y",
            "-f", "concat", "-safe", "0",
            "-i", concat_file,
            "-c:v", "prores_ks",
            "-profile:v", "4444",
            "-pix_fmt", "yuva444p10le",
            output_path,
        ], timeout=600)

    def _load_preview_frame(self, frames_dir):
        """Load first rendered frame as preview."""
        try:
            import numpy as np
            from PIL import Image

            frames_path = Path(frames_dir)
            frames = sorted(frames_path.glob("*.jpg")) + sorted(frames_path.glob("*.png"))
            if frames:
                img = Image.open(frames[0]).convert("RGB")
                img = img.resize((640, 360))
                return self._numpy_to_comfy_image(np.array(img).astype(np.float32) / 255.0)
        except Exception:
            pass
        return self._create_error_image("No rendered frames yet")

    def _export_ply_from_checkpoint(self, model_path, ply_dir, dataset_info):
        """
        Provide PLY point cloud files for the 3D viewer.

        Strategy (in order of preference):
        1. Extract trained positions from checkpoint + filter by multi-view mask
           projection to produce surface-only point clouds (not the full volume).
        2. Fallback: copy surfs/ PLY files (visual hull — cube-shaped volume).
        """
        os.makedirs(ply_dir, exist_ok=True)

        # Check if PLYs already exist and are up-to-date with the checkpoint
        existing = [f for f in os.listdir(ply_dir) if f.endswith('.ply')] if os.path.isdir(ply_dir) else []
        if existing:
            # Check if checkpoint is newer than existing PLYs (stale after retrain)
            ply_mtime = max(
                os.path.getmtime(os.path.join(ply_dir, f)) for f in existing
            )
            ckpt_mtime = os.path.getmtime(model_path) if model_path and os.path.isfile(model_path) else 0
            if ckpt_mtime > ply_mtime:
                self._node_logger.info(
                    "Checkpoint is newer than existing PLYs — regenerating"
                )
                import shutil
                shutil.rmtree(ply_dir)
                os.makedirs(ply_dir, exist_ok=True)
            else:
                self._node_logger.info(f"PLY files already exist in {ply_dir} ({len(existing)} files), skipping export")
                return

        # Strategy 1: Mask-filtered export from checkpoint + camera data
        try:
            if self._export_mask_filtered_ply(model_path, ply_dir, dataset_info):
                return
        except Exception as e:
            self._node_logger.warning(f"Mask-filtered PLY export failed: {e}")

        # Strategy 2: Fallback — copy surfs/vhulls PLYs (visual hull volume)
        if self._copy_surfs_plys(ply_dir, dataset_info):
            return

        # Strategy 3: Raw checkpoint export
        if model_path and os.path.isfile(model_path):
            try:
                self._export_from_checkpoint_file(model_path, ply_dir)
                exported = [f for f in os.listdir(ply_dir) if f.endswith('.ply')]
                if exported:
                    return
            except Exception as e:
                self._node_logger.warning(f"Checkpoint PLY export failed: {e}")

        self._node_logger.warning("No PLY data source found for 3D viewer")

    def _export_mask_filtered_ply(self, model_path, ply_dir, dataset_info):
        """
        Extract trained point positions from checkpoint, project to camera views,
        filter by foreground masks, and color by sampling input images.

        This produces a surface-only point cloud that matches the rendered video,
        instead of the full volumetric visual hull (cube shape).

        Returns True if successful.
        """
        import numpy as np

        dataset_root = dataset_info.get("dataset_root", "")
        if not dataset_root:
            return False

        # ── Load camera calibration ──────────────────────────────────────
        intri_path = os.path.join(dataset_root, "intri.yml")
        extri_path = os.path.join(dataset_root, "extri.yml")
        if not os.path.isfile(intri_path) or not os.path.isfile(extri_path):
            self._node_logger.warning("Camera calibration files not found, cannot do mask filtering")
            return False

        cameras = self._load_opencv_cameras(intri_path, extri_path)
        if not cameras:
            self._node_logger.warning("Failed to parse camera calibration")
            return False

        self._node_logger.info(f"Loaded {len(cameras)} cameras for mask-filtered export")

        # ── Load trained positions from checkpoint ───────────────────────
        positions_per_frame = self._load_checkpoint_positions(model_path)
        if positions_per_frame is None:
            self._node_logger.warning("Could not load positions from checkpoint")
            return False

        n_frames = len(positions_per_frame)
        self._node_logger.info(f"Loaded {n_frames} frames from checkpoint, {positions_per_frame[0].shape[0]} points each")

        # ── Load masks and images for each camera ────────────────────────
        images_dir = os.path.join(dataset_root, "images")
        mask_dir = os.path.join(dataset_root, "mask")
        if not os.path.isdir(mask_dir):
            mask_dir = os.path.join(dataset_root, "masks")

        cam_names = sorted(os.listdir(images_dir)) if os.path.isdir(images_dir) else []
        if not cam_names:
            self._node_logger.warning("No camera image directories found")
            return False

        # ── Process each frame ───────────────────────────────────────────
        min_visible = max(2, len(cameras) // 2)  # visible in at least half the cameras
        os.makedirs(ply_dir, exist_ok=True)
        exported_count = 0

        for frame_idx in range(n_frames):
            positions = positions_per_frame[frame_idx]  # (N, 3)
            n_points = positions.shape[0]

            # Track visibility and accumulated colors
            visibility_count = np.zeros(n_points, dtype=np.int32)
            color_accum = np.zeros((n_points, 3), dtype=np.float64)
            color_count = np.zeros(n_points, dtype=np.int32)

            for cam_idx, cam_name in enumerate(cam_names):
                if cam_name not in cameras:
                    continue

                cam = cameras[cam_name]
                K = cam["K"]       # 3x3 intrinsic
                R = cam["R"]       # 3x3 rotation
                T = cam["T"]       # 3x1 translation

                # Load mask for this camera+frame
                mask_cam_dir = os.path.join(mask_dir, cam_name)
                mask_img = self._load_frame_image(mask_cam_dir, frame_idx, grayscale=True)

                # Load color image for this camera+frame
                img_cam_dir = os.path.join(images_dir, cam_name)
                color_img = self._load_frame_image(img_cam_dir, frame_idx, grayscale=False)

                if mask_img is None:
                    continue

                h, w = mask_img.shape[:2]

                # Project all points: p_cam = R @ p_world + T
                p_cam = (R @ positions.T + T).T  # (N, 3)

                # Filter points behind camera
                valid_depth = p_cam[:, 2] > 0.01

                # Project to pixel coordinates: p_px = K @ p_cam
                p_px = (K @ p_cam.T).T  # (N, 3)
                px_x = p_px[:, 0] / (p_px[:, 2] + 1e-8)
                px_y = p_px[:, 1] / (p_px[:, 2] + 1e-8)

                # Check bounds
                in_bounds = (
                    valid_depth &
                    (px_x >= 0) & (px_x < w - 1) &
                    (px_y >= 0) & (px_y < h - 1)
                )

                # Sample mask at projected positions
                ix = np.clip(px_x.astype(np.int32), 0, w - 1)
                iy = np.clip(px_y.astype(np.int32), 0, h - 1)

                mask_vals = mask_img[iy, ix]
                # Mask is foreground if > 128 (white = foreground)
                is_foreground = in_bounds & (mask_vals > 128)

                visibility_count += is_foreground.astype(np.int32)

                # Sample color from input image
                if color_img is not None:
                    fg_indices = np.where(is_foreground)[0]
                    if len(fg_indices) > 0:
                        sampled_colors = color_img[iy[fg_indices], ix[fg_indices]]
                        if sampled_colors.ndim == 1:
                            sampled_colors = sampled_colors.reshape(-1, 1)
                        if sampled_colors.shape[-1] == 1:
                            sampled_colors = np.tile(sampled_colors, (1, 3))
                        color_accum[fg_indices] += sampled_colors[:, :3].astype(np.float64)
                        color_count[fg_indices] += 1

            # ── Filter by visibility ─────────────────────────────────────
            keep_mask = visibility_count >= min_visible
            kept_positions = positions[keep_mask]

            # Average colors
            kept_color_count = color_count[keep_mask]
            kept_color_accum = color_accum[keep_mask]

            # Avoid division by zero
            safe_count = np.maximum(kept_color_count, 1)
            kept_colors = (kept_color_accum / safe_count[:, np.newaxis]).astype(np.uint8)

            # Points with no color samples get light gray
            no_color = kept_color_count == 0
            kept_colors[no_color] = 200

            n_kept = kept_positions.shape[0]
            self._node_logger.info(
                f"Frame {frame_idx}: {n_kept}/{n_points} points passed mask filter "
                f"(visible in >= {min_visible}/{len(cameras)} cameras)"
            )

            if n_kept > 0:
                ply_path = os.path.join(ply_dir, f"frame_{frame_idx:06d}.ply")
                self._write_binary_ply(ply_path, kept_positions, kept_colors)
                exported_count += 1

        if exported_count > 0:
            self._node_logger.info(f"Exported {exported_count} mask-filtered PLY files to {ply_dir}")
            return True
        return False

    def _load_opencv_cameras(self, intri_path, extri_path):
        """
        Parse OpenCV-format YAML camera calibration files.

        Returns dict of camera_name -> {"K": 3x3, "R": 3x3, "T": 3x1}
        """
        import numpy as np

        def parse_opencv_yaml(path):
            """Parse OpenCV YAML file (has %YAML:1.0 header that pyyaml can't handle)."""
            with open(path, 'r') as f:
                content = f.read()

            # Strip OpenCV YAML directive that standard parsers choke on
            lines = content.split('\n')
            clean_lines = [l for l in lines if not l.startswith('%YAML')]
            clean = '\n'.join(clean_lines)

            try:
                import yaml
                return yaml.safe_load(clean)
            except Exception:
                pass

            # Manual fallback parser for opencv-matrix entries
            result = {}
            current_key = None
            current_obj = {}

            for line in lines:
                line = line.rstrip()
                if line.startswith('%') or line == '---':
                    continue

                if ':' in line and not line.startswith(' ') and not line.startswith('\t'):
                    # Top-level key
                    if current_key and current_obj:
                        result[current_key] = current_obj
                    parts = line.split(':', 1)
                    current_key = parts[0].strip()
                    val = parts[1].strip() if len(parts) > 1 else ''
                    if val and not val.startswith('!!'):
                        # Simple value
                        result[current_key] = val
                        current_key = None
                        current_obj = {}
                    else:
                        current_obj = {}
                elif current_key and ':' in line:
                    parts = line.strip().split(':', 1)
                    k = parts[0].strip()
                    v = parts[1].strip() if len(parts) > 1 else ''
                    if k == 'data':
                        # Parse array: [ 1., 2., 3. ]
                        v = v.strip('[] ')
                        try:
                            current_obj[k] = [float(x.strip()) for x in v.split(',') if x.strip()]
                        except ValueError:
                            current_obj[k] = v
                    else:
                        try:
                            current_obj[k] = int(v)
                        except (ValueError, TypeError):
                            try:
                                current_obj[k] = float(v)
                            except (ValueError, TypeError):
                                current_obj[k] = v

            if current_key and current_obj:
                result[current_key] = current_obj

            return result

        try:
            intri = parse_opencv_yaml(intri_path)
            extri = parse_opencv_yaml(extri_path)
        except Exception as e:
            self._node_logger.warning(f"Failed to parse camera YAML: {e}")
            return {}

        # Extract camera names
        names = extri.get("names", [])
        if isinstance(names, dict):
            # Sometimes parsed as dict
            names = list(names.values()) if names else []
        elif isinstance(names, str):
            names = [n.strip().strip('"').strip("'") for n in names.split(',')]

        if not names:
            # Try to discover from keys like K_00, K_01...
            for key in intri:
                if key.startswith("K_"):
                    cam_id = key[2:]
                    if cam_id not in names:
                        names.append(cam_id)
            names = sorted(names)

        cameras = {}
        for name in names:
            name_str = str(name).strip('"').strip("'")

            # Intrinsic matrix K
            k_key = f"K_{name_str}"
            k_data = intri.get(k_key, {})
            if isinstance(k_data, dict) and 'data' in k_data:
                K = np.array(k_data['data'], dtype=np.float64).reshape(3, 3)
            else:
                continue

            # Rotation R (Rodrigues vector)
            r_key = f"R_{name_str}"
            r_data = extri.get(r_key, {})
            if isinstance(r_data, dict) and 'data' in r_data:
                r_vec = np.array(r_data['data'], dtype=np.float64)
                if r_vec.size == 3:
                    # Rodrigues vector → rotation matrix
                    angle = np.linalg.norm(r_vec)
                    if angle < 1e-8:
                        R = np.eye(3)
                    else:
                        k = r_vec / angle
                        K_cross = np.array([
                            [0, -k[2], k[1]],
                            [k[2], 0, -k[0]],
                            [-k[1], k[0], 0]
                        ])
                        R = np.eye(3) + np.sin(angle) * K_cross + (1 - np.cos(angle)) * (K_cross @ K_cross)
                elif r_vec.size == 9:
                    R = r_vec.reshape(3, 3)
                else:
                    R = np.eye(3)
            else:
                R = np.eye(3)

            # Translation T
            t_key = f"T_{name_str}"
            t_data = extri.get(t_key, {})
            if isinstance(t_data, dict) and 'data' in t_data:
                T = np.array(t_data['data'], dtype=np.float64).reshape(3, 1)
            else:
                T = np.zeros((3, 1))

            cameras[name_str] = {"K": K, "R": R, "T": T}

        return cameras

    def _load_checkpoint_positions(self, model_path):
        """
        Load per-frame point positions from the trained checkpoint.

        Returns list of numpy arrays, one per frame, each shape (N, 3).
        Falls back to .npz sibling if model_path is .pt.
        """
        import numpy as np

        # Prefer .npz for positions (smaller, faster to load than .pt)
        npz_path = model_path
        if model_path.endswith('.pt') or model_path.endswith('.pth'):
            npz_path = model_path.rsplit('.', 1)[0] + '.npz'

        if os.path.isfile(npz_path):
            try:
                data = np.load(npz_path, allow_pickle=True)
                keys = list(data.keys())

                # Find sampler.pcds.N keys
                pcd_keys = sorted([k for k in keys if k.startswith('sampler.pcds.')])
                if pcd_keys:
                    frames = []
                    for k in pcd_keys:
                        arr = data[k]
                        if arr.ndim == 2 and arr.shape[-1] == 3:
                            frames.append(arr.astype(np.float32))
                    if frames:
                        return frames
            except Exception as e:
                self._node_logger.warning(f"Failed to load NPZ positions: {e}")

        # Fallback: try .pt file
        if os.path.isfile(model_path) and (model_path.endswith('.pt') or model_path.endswith('.pth')):
            try:
                import torch
                ckpt = torch.load(model_path, map_location='cpu', weights_only=False)
                state = ckpt.get('model', ckpt)
                if isinstance(state, dict):
                    pcd_keys = sorted([k for k in state.keys() if 'pcds' in k.lower()])
                    frames = []
                    for k in pcd_keys:
                        t = state[k]
                        if hasattr(t, 'numpy'):
                            t = t.numpy()
                        if t.ndim == 2 and t.shape[-1] == 3:
                            frames.append(t.astype(np.float32))
                    if frames:
                        return frames
            except Exception as e:
                self._node_logger.warning(f"Failed to load PT positions: {e}")

        return None

    def _load_frame_image(self, cam_dir, frame_idx, grayscale=False):
        """Load an image from a camera directory by frame index."""
        import numpy as np

        if not os.path.isdir(cam_dir):
            return None

        files = sorted([
            f for f in os.listdir(cam_dir)
            if f.lower().endswith(('.png', '.jpg', '.jpeg'))
        ])
        if not files:
            return None

        # Clamp frame index
        idx = min(frame_idx, len(files) - 1)
        img_path = os.path.join(cam_dir, files[idx])

        try:
            from PIL import Image
            img = Image.open(img_path)
            if grayscale:
                img = img.convert('L')
                return np.array(img)
            else:
                img = img.convert('RGB')
                return np.array(img)
        except Exception:
            return None

    def _write_binary_ply(self, ply_path, positions, colors):
        """Write a binary little-endian PLY file with positions and RGB colors."""
        import numpy as np

        pos = positions.reshape(-1, 3).astype(np.float32)
        n = pos.shape[0]

        if colors is not None:
            col = colors.reshape(-1, colors.shape[-1]).astype(np.float32)
            # Take only RGB (drop alpha if present)
            if col.shape[-1] > 3:
                col = col[:, :3]
            # Normalize to 0-255
            if col.max() <= 1.0 + 1e-6:
                col = (np.clip(col, 0.0, 1.0) * 255).astype(np.uint8)
            else:
                col = np.clip(col, 0, 255).astype(np.uint8)
            # Truncate or pad if count doesn't match positions
            if col.shape[0] < n:
                pad = np.full((n - col.shape[0], 3), 200, dtype=np.uint8)
                col = np.concatenate([col, pad], axis=0)
            elif col.shape[0] > n:
                col = col[:n]
        else:
            col = np.full((n, 3), 200, dtype=np.uint8)  # light gray

        header = (
            "ply\n"
            "format binary_little_endian 1.0\n"
            f"element vertex {n}\n"
            "property float x\n"
            "property float y\n"
            "property float z\n"
            "property uchar red\n"
            "property uchar green\n"
            "property uchar blue\n"
            "end_header\n"
        )

        with open(ply_path, 'wb') as f:
            f.write(header.encode('ascii'))
            # Write interleaved position + color data efficiently
            for i in range(n):
                f.write(struct.pack('<fff', float(pos[i, 0]), float(pos[i, 1]), float(pos[i, 2])))
                f.write(struct.pack('BBB', int(col[i, 0]), int(col[i, 1]), int(col[i, 2])))

    def _copy_surfs_plys(self, ply_dir, dataset_info):
        """
        Copy preprocessed surface/vhull PLY files to the viewer PLY directory.

        Looks in surfs/ (EasyVolcap preprocessing output) and vhulls/ as fallback.
        Returns True if PLY files were found and copied.
        """
        import shutil

        dataset_root = dataset_info.get("dataset_root", "")
        # surfs/ is the primary output from EasyVolcap preprocessing (visual hull)
        # vhulls/ is an alternative name used by some pipeline versions
        for subdir in ("surfs", "vhulls"):
            source_dir = os.path.join(dataset_root, subdir)
            if not os.path.isdir(source_dir):
                continue

            ply_files = sorted([f for f in os.listdir(source_dir) if f.endswith('.ply')])
            if not ply_files:
                continue

            os.makedirs(ply_dir, exist_ok=True)
            for i, fname in enumerate(ply_files):
                src = os.path.join(source_dir, fname)
                dst = os.path.join(ply_dir, f"frame_{i:06d}.ply")
                if not os.path.exists(dst):
                    shutil.copy2(src, dst)

            self._node_logger.info(
                f"Copied {len(ply_files)} PLY files from {source_dir} to {ply_dir}"
            )
            return True

        return False

    def _export_from_checkpoint_file(self, model_path, ply_dir):
        """
        Try to extract point cloud data from a trained model checkpoint.
        Supports both PyTorch (.pt/.pth) and NumPy (.npz) formats.
        """
        import numpy as np

        ext = os.path.splitext(model_path)[1].lower()

        if ext in ('.pt', '.pth', '.ckpt'):
            self._export_from_pytorch_checkpoint(model_path, ply_dir)
        elif ext == '.npz':
            self._export_from_npz_checkpoint(model_path, ply_dir)
        else:
            self._node_logger.warning(f"Unknown checkpoint format: {ext}")

    def _export_from_pytorch_checkpoint(self, model_path, ply_dir):
        """Extract point cloud from PyTorch checkpoint."""
        import numpy as np
        import torch

        self._node_logger.info(f"Loading PyTorch checkpoint: {model_path}")
        data = torch.load(model_path, map_location='cpu', weights_only=False)

        # PyTorch checkpoints may be a state_dict or have 'state_dict' key
        if isinstance(data, dict) and 'state_dict' in data:
            data = data['state_dict']
        elif isinstance(data, dict) and 'model' in data:
            data = data['model']

        if not isinstance(data, dict):
            self._node_logger.warning(f"Unexpected checkpoint type: {type(data)}")
            return

        keys = list(data.keys())
        self._node_logger.info(f"Checkpoint keys ({len(keys)}): {keys[:30]}")

        # Find position and color tensors
        pos, colors = self._find_pos_color_in_dict(data, keys)
        if pos is None:
            self._node_logger.warning(f"No position data found in PyTorch checkpoint")
            return

        self._write_ply_from_arrays(ply_dir, pos, colors)

    def _export_from_npz_checkpoint(self, model_path, ply_dir):
        """Extract point cloud from NumPy .npz checkpoint."""
        import numpy as np

        self._node_logger.info(f"Loading NPZ checkpoint: {model_path}")
        data = np.load(model_path, allow_pickle=True)
        keys = list(data.keys())
        self._node_logger.info(f"NPZ keys ({len(keys)}): {keys[:30]}")

        pos, colors = self._find_pos_color_in_dict(data, keys)
        if pos is None:
            self._node_logger.warning(f"No position data found in NPZ checkpoint")
            return

        self._write_ply_from_arrays(ply_dir, pos, colors)

    def _find_pos_color_in_dict(self, data, keys):
        """Find position and color arrays in a checkpoint dict."""
        import numpy as np

        pos = None
        colors = None

        # Position candidates
        for k in keys:
            kl = k.lower()
            if any(sub in kl for sub in ['xyz', 'position', 'means3d', '.pcd', 'point']):
                arr = data[k]
                if hasattr(arr, 'numpy'):
                    arr = arr.numpy()  # torch tensor → numpy
                if hasattr(arr, 'shape') and arr.ndim >= 2 and arr.shape[-1] == 3:
                    pos = arr
                    self._node_logger.info(f"Position key: '{k}' shape={arr.shape}")
                    break

        # Color candidates
        for k in keys:
            kl = k.lower()
            if any(sub in kl for sub in ['rgb', 'color', 'feature_dc', 'sh_coef']):
                arr = data[k]
                if hasattr(arr, 'numpy'):
                    arr = arr.numpy()
                if hasattr(arr, 'shape') and arr.ndim >= 2 and arr.shape[-1] in (3, 4):
                    colors = arr
                    self._node_logger.info(f"Color key: '{k}' shape={arr.shape}")
                    break

        return pos, colors

    def _write_ply_from_arrays(self, ply_dir, pos, colors):
        """Write PLY files from position/color numpy arrays."""
        import numpy as np

        if pos.ndim == 3:
            n_frames = pos.shape[0]
            self._node_logger.info(f"Temporal: {n_frames} frames, {pos.shape[1]} points each")
            for t in range(n_frames):
                frame_colors = colors[t] if colors is not None and colors.ndim == 3 else colors
                ply_path = os.path.join(ply_dir, f"frame_{t:06d}.ply")
                self._write_binary_ply(ply_path, pos[t], frame_colors)
        elif pos.ndim == 2:
            ply_path = os.path.join(ply_dir, "frame_000000.ply")
            self._write_binary_ply(ply_path, pos, colors)
            self._node_logger.info(f"Exported {pos.shape[0]} points to {ply_path}")
